spring:
  cloud:
    gateway:
      routes:
        - id: customerModule
          uri: http://localhost:8081/
          predicates:
            - Path=/customers/**
        - id: productModule
          uri: http://localhost:8082/
          predicates:
            - Path=/products/**
    discovery:
      enabled: false
server:
  port: 8888

